# Write the code that execute the following:

### Output:  We School

In [2]:
print("we school")

we school

### Declare variable with initial value 6 and print it

In [9]:
x=2
y=3
print(y*x)

6

### Declare variable with initial value your name and print it

In [10]:
x="youssef"
y="magd"
print(x+y)

youssefmagd

### Print the following output (WeSchool 2021) by using two variables

In [16]:
z="weschool"
y="2021"
print(z+y)

weschool2021

### Declare three variables x,y & z with initial values 1,2 & 3 in one line then print them

In [13]:
(z,y,x)=(1,2,3)
print(z)
print(y)
print(x)

1
2
3

### Declare variable a with initial value 2.0 and get it's data type by using type function, repeat by another variables with another data types

In [15]:
x=2.0
print(type(x))
y=2
print(type(y))

<class 'float'>
<class 'int'>

### Declare string variable with value "I am in we school, grade 1"  ,then:

In [19]:
x="iamin"
y="weschool"
z=",grade1"
print(x+y+z)

iaminweschool,grade1

#### 1) get length of it

In [20]:
len(x+y+z)

20

#### 2) check if word "WE" is in the string or not

In [21]:
type("we")

str

#### 3)Modify string to "I am in we school,grade 2" by using replace() method

In [15]:
text="iaminweschool,grade1"
print(text)

iaminweschool,grade1

In [16]:
print(text.replace("1","2"))

iaminweschool,grade2

#### 4)Modify string to be in uppercase (capital letters)

In [18]:
print(text.upper)

<built-in method upper of str object at 0x7f924c68c8a0>

#### 5) Split string on every white space (  )

In [23]:
print(text.split(  )

SyntaxError: unexpected EOF while parsing (<ipython-input-23-7fae911c751d>, line 1)

#### 6) Write the sring by format method with words "I" and "we" and "school" as variables

In [20]:
x="iam"
y="inwe"
z="school"
print(x+y+z)

iaminweschool

### Divide 11 by 2 and get result in float form

In [3]:
x=11/2
print(x)

5.5

### Divide 11 by 2 and get result in integer form

In [4]:
x=11//2
print(x)

5

### Divide 11 by 2 and get result in string form by using casting

In [5]:
x=11//2
z=str(x)
print(z)

5

### Get the reminder when you divide 11 by 2

In [7]:
11%2

1

### Make user enter his age as input, then add 5 to his age. (make the required to prevent error ocuured)

In [14]:
x=input("age+5")

age+5 20

### Declare variable with boolean value, then print it's type by using type function

In [15]:
x="False"
print(type(x))

<class 'str'>

In [15]:
z=False
print(type(z))

<class 'str'>

### Declare this list in variable ['tennis','swimmig','pingpong','handball','volley']

In [26]:
x=["tennis","swimming","pingpong","handball","volleyball"]
print(x)

['tennis', 'swimming', 'pingpong', 'handball', 'volleyball']

### 1) access item "pingpong" from the list

In [18]:
print(x[2])

pingpong

### 2) access items from swimming to handball in list by using range index

In [19]:
print(x[1:4])

['swimming', 'pingpong', 'handball']

### 3) Modify list to be ['tennis','swimming','pingpong','football','volley'] without declaring new list

In [6]:
print(x)

['tennis', 'swimming', 'pingpong', 'handball', 'volleyball']

In [27]:
x=["tennis","swimming","pingpong","handball","volleyball"]
print(x)

['tennis', 'swimming', 'pingpong', 'handball', 'volleyball']

In [28]:
x.remove("handball")
x.insert(3,"football")
print(x)

['tennis', 'swimming', 'pingpong', 'football', 'volleyball']

### 4) add item 'squash' at order number 3 in list

In [29]:
print(x)

['tennis', 'swimming', 'pingpong', 'football', 'volleyball']

In [30]:
x[3]="squash"
print(x)

['tennis', 'swimming', 'pingpong', 'squash', 'volleyball']

### 5) add item 'karatee' at the end of the list

In [31]:
x.append("karate")
print(x)

['tennis', 'swimming', 'pingpong', 'squash', 'volleyball', 'karate']

### 6) remove 'tennis' from list

In [32]:
x.remove("tennis")
print(x)

['swimming', 'pingpong', 'squash', 'volleyball', 'karate']

### 7) Sort this list in both ascending and descending orders

In [35]:
x.sort(reverse=True)
print(x)

['volleyball', 'swimming', 'squash', 'pingpong', 'karate']

### 8)Declare new list ['running','walking'] then merge it with the main previous list

In [36]:
x=["running","walking"]
x.append("play")
x.remove("walking")
x.sort(reverse=True)
print(x)

['running', 'play']